### ISSUE TITLE
I am unable to upload my example files

### ISSUE THREAD

**Issue by sahirsharuz** [LeeMorinUCF/GEB6895F19#35]
Hello Professor,

I am having difficulty adding my files in my fork. I don't know what I am doing wrong. I tried seeking help online and helpless. 

I don't want to lose any points, however, I have finished coding all the problems so far. 

What can I do?

**Comment by LeeMorinUCF** [comment]
Hi Sahir,

Maybe I can help. Just to be clear,  did you create the material on your laptop? Did you then go through the steps to add, commit and push? If so, at which step does it give you an error?

Please send a screenshot of the error and I can use that to troubleshoot your problem.

Best,

LM

Get Outlook for Android<https://aka.ms/ghei36>



From: sahirsharuz
Sent: Friday, September 13, 7:19 PM
Subject: [LeeMorinUCF/GEB6895F19] I am unable to upload my example files (#35)
To: LeeMorinUCF/GEB6895F19
Cc: Subscribed


Hello Professor,
I am having difficulty adding my files in my fork. I don't know what I am doing wrong. I tried seeking help online and helpless.
I don't want to lose any points, however, I have finished coding all the problems so far.
What can I do?

**Comment by sahirsharuz** [comment]
![git add and push](https://user-images.githubusercontent.com/54648794/64925289-4f8d6200-d7bc-11e9-9a09-7d6666f15584.PNG)
![git hub assignment 1 ](https://user-images.githubusercontent.com/54648794/64925290-4f8d6200-d7bc-11e9-897c-fb9508e46994.png)
![git push origin master](https://user-images.githubusercontent.com/54648794/64925291-4f8d6200-d7bc-11e9-8aae-a65ca1f9e91c.PNG)
![github snap shot](https://user-images.githubusercontent.com/54648794/64925292-5025f880-d7bc-11e9-81c6-1b6cbb4572ee.png)

**Comment by sahirsharuz** [comment]
I finished all the examples however, I am trying to just push two examples, example_01.R, & example_02.R. No luck!

**Comment by LeeMorinUCF** [comment]
Hi Sahir,

Thanks for the detailed description of your problem. I can see that you are adding the file and trying to push it but you skipped the commit step:

git commit -m 'completed example 1'

Then do the push command.

Of the two versions that you have shown,  you should continue on the second, which is done in your fork. The LeeMorinUCF repo will add your solutions to the original repo instead of your fork.



Best,
LM

Get Outlook for Android<https://aka.ms/ghei36>

________________________________
