### ISSUE TITLE
Making Fork Private 

### ISSUE THREAD

**Issue by lara-willson** [LeeMorinUCF/GEB6895F19#36]
I'm struggling to make my fork private - I'm receiving the error message below. Is this expected? I have googled a work around that involves mirroring the fork, but it seems slightly more complicated than the announcement made it seem, so I just wanted to see if I was missing something obvious, or made a mistake on a step somewhere.

![image](https://user-images.githubusercontent.com/54648873/64901778-23160080-d66b-11e9-8144-bfe63899b83f.png)

Thanks in advance for the help! :)

**Comment by LeeMorinUCF** [comment]
Hi Lara,

Thanks for pointing this out. Because of this difficulty, I have postponed the privacy component until I can walk us through it during the next lecture. Rest assured that I will maintain privacy of the feedback on your work.


Best wishes,
Lealand Morin, Ph.D.
Assistant Professor
Department of Economics
UCF College of Business
Office: 407.823.4468
Lealand.Morin@ucf.edu<mailto:Lealand.Morin@ucf.edu>
business.ucf.edu
